// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyPlaces.Model;

namespace MyPlaces.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("MyPlaces.Model.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latidude")
                        .HasColumnType("float");

                    b.Property<double>("Longtidude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathToImage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Spodziewałem się czegoś więcej",
                            Latidude = 41.890239999999999,
                            Longtidude = 12.492369999999999,
                            Name = "Koloseum",
                            PathToImage = ""
                        },
                        new
                        {
                            Id = 2,
                            Description = "Urokliwe miejsce",
                            Latidude = 38.895330000000001,
                            Longtidude = 8.8851099999999992,
                            Name = "Torre di Chia",
                            PathToImage = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
